"""
modules/md_header.py — Metadata header management for .md pipeline artifacts.

Writes a standardised HTML-comment header at the top of every .md artifact,
mirroring the pattern established in specwright_spec_<slug>.md.

Header format (2 lines):
    <!-- {artifact_name} — {action} by {owner} on {iso_timestamp} -->
    <!-- project: {project} | model: {model} -->

"created" vs "modified":
    - First write  → action = "generated"
    - Subsequent   → action = "modified"
    created timestamp is preserved from the existing header on update.

────────────────────────────────────────────────────────────────────────────────
Usage per script
────────────────────────────────────────────────────────────────────────────────
    from modules.md_header import apply_header
    from artifacts.models import get_model
    from artifacts.paths import ENRICHER_OVERWRITE_PROMPT

    # Before writing any .md artifact:
    final_content = apply_header(
        content  = enriched_text,
        path     = ENRICHER_OVERWRITE_PROMPT,
        owner    = "03_enricher.py",
        model    = get_model(ROLE),          # omit if script has no LLM call
    )
    ENRICHER_OVERWRITE_PROMPT.write_text(final_content, encoding="utf-8")

────────────────────────────────────────────────────────────────────────────────
Note on specwright
────────────────────────────────────────────────────────────────────────────────
specwright_spec_<slug>.md has its own header logic with versioning
(# Version: line required by spectracker regex) and two sub-actions
("generated by" / "edited by user"). That script manages its own header
and does NOT use this module.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ─── Regex to parse an existing header ───────────────────────────────────────
# Matches the first comment line to extract the created/generated timestamp.
# Tolerant of both "generated" and "modified" action words.

_HEADER_RE = re.compile(
    r"^<!--\s*\S+\s*[—-]\s*(?:generated|modified)\s+by\s+\S+\s+on\s+(\S+)\s*-->",
    re.MULTILINE,
)

_PROJECT_LINE_RE = re.compile(
    r"^<!--\s*project:.*?-->\s*\n?",
    re.MULTILINE,
)

# Number of header lines to strip when replacing an existing header
_HEADER_LINE_COUNT = 2


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _parse_created_ts(existing_content: str) -> str | None:
    """Extract the original created/generated timestamp from an existing header."""
    m = _HEADER_RE.search(existing_content)
    return m.group(1) if m else None


def _strip_existing_header(content: str) -> str:
    """Remove the first 2 header comment lines if present."""
    lines = content.splitlines(keepends=True)
    stripped = 0
    result = []
    for line in lines:
        if stripped < _HEADER_LINE_COUNT and line.startswith("<!--"):
            stripped += 1
            continue
        result.append(line)
    # Drop leading blank line left after header removal
    while result and result[0].strip() == "":
        result.pop(0)
    return "".join(result)


def make_header(
    artifact_name: str,
    owner:         str,
    *,
    action:        str         = "generated",
    created_ts:    str | None  = None,
    modified_ts:   str | None  = None,
    model:         str | None  = None,
    project:       str | None  = None,
) -> str:
    """
    Build the 2-line metadata header string (with trailing newline).

    Parameters
    ----------
    artifact_name : filename of the artifact (e.g. "enricher_session_enriched_prompt.md")
    owner         : script that owns this artifact (e.g. "03_enricher.py")
    action        : "generated" (first write) or "modified" (update)
    created_ts    : ISO timestamp of first creation; uses now if None
    modified_ts   : ISO timestamp of this write; uses now if None
    model         : model string (omit for non-LLM scripts)
    project       : project name; reads PIPELINE_PROJECT env var if None
    """
    now       = _now_iso()
    ts        = modified_ts or now
    created   = created_ts or now
    proj      = project or os.environ.get("PIPELINE_PROJECT", "unknown")

    line1_ts  = ts if action == "modified" else created
    line1     = f"<!-- {artifact_name} — {action} by {owner} on {line1_ts} -->"

    parts     = [f"project: {proj}"]
    if model:
        parts.append(f"model: {model}")
    if action == "modified":
        parts.append(f"created: {created}")
    line2 = "<!-- " + " | ".join(parts) + " -->"

    return f"{line1}\n{line2}\n\n"


def apply_header(
    content: str,
    path:    Any,
    owner:   str,
    *,
    model:   str | None = None,
    project: str | None = None,
) -> str:
    """
    Prepend (or replace) the metadata header on a .md artifact's content.

    - If the target file already exists and has a header → preserve created
      timestamp, set action = "modified".
    - If the file doesn't exist or has no header → action = "generated".

    Parameters
    ----------
    content : the new artifact content (without any header)
    path    : Path or str — destination file path (used to read existing header)
    owner   : owning script filename (e.g. "03_enricher.py")
    model   : model string if this is an LLM output artifact
    project : project name override (reads PIPELINE_PROJECT env var if None)

    Returns
    -------
    str — content with header prepended, ready to write to disk.
    """
    p            = Path(str(path))
    artifact_name = p.name
    created_ts   = None
    action       = "generated"

    if p.exists():
        try:
            existing = p.read_text(encoding="utf-8")
            created_ts = _parse_created_ts(existing)
            if created_ts:
                action = "modified"
        except OSError:
            pass

    header = make_header(
        artifact_name = artifact_name,
        owner         = owner,
        action        = action,
        created_ts    = created_ts,
        model         = model,
        project       = project,
    )

    # Strip any existing header from the incoming content (idempotent)
    clean = _strip_existing_header(content) if content.lstrip().startswith("<!--") else content

    return header + clean.strip() + "\n"
